### Import Required Libraries

In [5]:
import pandas as pd
import numpy as np

In [8]:
dict1 = {
    'investment in lakhs':[1,2,3,4,5],
    'revenue in crore':[2,4,5,4,5]
}

df = pd.DataFrame(dict1)

In [9]:
df

   investment in lakhs  revenue in crore
0                    1                 2
1                    2                 4
2                    3                 5
3                    4                 4
4                    5                 5

In [21]:
df[['investment in lakhs']]

   investment in lakhs
0                    1
1                    2
2                    3
3                    4
4                    5

In [22]:
df['revenue in crore']

0    2
1    4
2    5
3    4
4    5
Name: revenue in crore, dtype: int64

In [10]:
X = df[['investment in lakhs']] # 2d
y = df['revenue in crore'] # 1d

In [14]:
# importing libraries
from sklearn.linear_model import LinearRegression

# create a instance/object
lr = LinearRegression()

# fitting our model
lr.fit(X,y)

# predicting 
ypred = lr.predict(X)

In [15]:
ypred

array([2.8, 3.4, 4. , 4.6, 5.2])

In [17]:
print(y,end=' ')

0    2
1    4
2    5
3    4
4    5
Name: revenue in crore, dtype: int64

In [20]:
# r2score
from sklearn.metrics import r2_score

r2_score(y,ypred)

0.6000000000000001