### Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Reading and understanding data

In [5]:
df = pd.read_csv('data_titanic.csv')
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Initial
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

### dropping columns

In [6]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Initial'],
      dtype='object')

In [7]:
df.drop(columns = ['Unnamed: 0', 'PassengerId','Name','Ticket', 'Fare', 'Cabin','Initial'],inplace=True)

In [8]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

### Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

In [11]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    1  22.0      1      0         2
1         1       1    0  38.0      1      0         0
2         1       3    0  26.0      0      0         2
3         1       1    0  35.0      1      0         2
4         0       3    1  35.0      0      0         2

### Splitting data into x and y

In [12]:
x = df.drop(columns = 'Survived')
y = df['Survived']

### Splitting data into train and test

In [13]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=1)

### Kernel
- Kernel : Kernel is used to handle non-linear data.
- kernel is also one of hyperparameter
- Type of kernel
- 1. Sigmoid - used in Layers(Neural network) and activation function.
  2. tanh - used in Layers(Neural network) and activation function.
  3. linear - when the data is linearly seperable we can use linear kernel.
  4. RBF(Radial basis kernel) - Gausian kernel mostly used when we don't have prior knowledge about the data.This is default kernel.
  5. Poly kernel - This kernel is widely used in image processing.

### Model1

In [16]:
# import class
from sklearn.svm import SVC

# create instance 
svm = SVC()

# fit the model
svm.fit(xtrain,ytrain)

# predict
ypred = svm.predict(xtest)

In [17]:
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.60      0.95      0.74       106
           1       0.58      0.10      0.16        73

    accuracy                           0.60       179
   macro avg       0.59      0.52      0.45       179
weighted avg       0.60      0.60      0.51       179

### Model2

In [18]:
# import class
from sklearn.svm import SVC

# create instance 
svm = SVC(kernel='linear')

# fit the model
svm.fit(xtrain,ytrain)

# predict
ypred = svm.predict(xtest)
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82       106
           1       0.75      0.67      0.71        73

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.76       179
weighted avg       0.77      0.78      0.77       179

### Grid Search CV

- Helps in hypertunning making grid(table)
- It Automatically build model using hypertunning and in the end it will give us best model with hypertunning

In [29]:
param_grid = {'C':[1,10,100],'gamma':[1,10,100]}

In [30]:
from sklearn.model_selection import GridSearchCV

gs = GridSearchCV(svm,param_grid,verbose=3)

gs.fit(xtrain,ytrain)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5] END ......................C=1, gamma=1;, score=0.741 total time=   0.3s
[CV 2/5] END ......................C=1, gamma=1;, score=0.776 total time=   0.2s
[CV 3/5] END ......................C=1, gamma=1;, score=0.817 total time=   0.3s
[CV 4/5] END ......................C=1, gamma=1;, score=0.824 total time=   0.1s
[CV 5/5] END ......................C=1, gamma=1;, score=0.789 total time=   0.0s
[CV 1/5] END .....................C=1, gamma=10;, score=0.741 total time=   0.0s
[CV 2/5] END .....................C=1, gamma=10;, score=0.776 total time=   0.0s
[CV 3/5] END .....................C=1, gamma=10;, score=0.817 total time=   0.0s
[CV 4/5] END .....................C=1, gamma=10;, score=0.824 total time=   0.0s
[CV 5/5] END .....................C=1, gamma=10;, score=0.789 total time=   0.0s
[CV 1/5] END ....................C=1, gamma=100;, score=0.741 total time=   0.0s
[CV 2/5] END ....................C=1, gamma=100;, score=0.776 total time=   0.0s
[CV 3/5] END ....................C=1, gamma=100;, score=0.817 total time=   0.0s
[CV 4/5] END ....................C=1, gamma=100;, score=0.824 total time=   0.1s
[CV 5/5] END ....................C=1, gamma=100;, score=0.789 total time=   0.0s
[CV 1/5] END .....................C=10, gamma=1;, score=0.741 total time=   1.0s
[CV 2/5] END .....................C=10, gamma=1;, score=0.776 total time=   0.3s
[CV 3/5] END .....................C=10, gamma=1;, score=0.817 total time=   0.4s
[CV 4/5] END .....................C=10, gamma=1;, score=0.824 total time=   0.5s
[CV 5/5] END .....................C=10, gamma=1;, score=0.789 total time=   0.4s
[CV 1/5] END ....................C=10, gamma=10;, score=0.741 total time=   0.6s
[CV 2/5] END ....................C=10, gamma=10;, score=0.776 total time=   0.3s
[CV 3/5] END ....................C=10, gamma=10;, score=0.817 total time=   0.4s
[CV 4/5] END ....................C=10, gamma=10;, score=0.824 total time=   0.6s
[CV 5/5] END ....................C=10, gamma=10;, score=0.789 total time=   0.4s
[CV 1/5] END ...................C=10, gamma=100;, score=0.741 total time=   0.6s
[CV 2/5] END ...................C=10, gamma=100;, score=0.776 total time=   0.3s
[CV 3/5] END ...................C=10, gamma=100;, score=0.817 total time=   0.5s
[CV 4/5] END ...................C=10, gamma=100;, score=0.824 total time=   1.2s
[CV 5/5] END ...................C=10, gamma=100;, score=0.789 total time=   0.5s
[CV 1/5] END ....................C=100, gamma=1;, score=0.741 total time=   8.0s
[CV 2/5] END ....................C=100, gamma=1;, score=0.776 total time=  10.2s
[CV 3/5] END ....................C=100, gamma=1;, score=0.817 total time=  15.4s
[CV 4/5] END ....................C=100, gamma=1;, score=0.824 total time=   6.5s
[CV 5/5] END ....................C=100, gamma=1;, score=0.789 total time=  13.1s
[CV 1/5] END ...................C=100, gamma=10;, score=0.741 total time=   6.4s
[CV 2/5] END ...................C=100, gamma=10;, score=0.776 total time=   7.9s
[CV 3/5] END ...................C=100, gamma=10;, score=0.817 total time=  11.9s
[CV 4/5] END ...................C=100, gamma=10;, score=0.824 total time=   4.9s
[CV 5/5] END ...................C=100, gamma=10;, score=0.789 total time=  11.5s
[CV 1/5] END ..................C=100, gamma=100;, score=0.741 total time=   6.4s
[CV 2/5] END ..................C=100, gamma=100;, score=0.776 total time=  10.8s
[CV 3/5] END ..................C=100, gamma=100;, score=0.817 total time=  17.8s
[CV 4/5] END ..................C=100, gamma=100;, score=0.824 total time=   5.0s
[CV 5/5] END ..................C=100, gamma=100;, score=0.789 total time=  11.8s

GridSearchCV(estimator=SVC(kernel='linear'),
             param_grid={'C': [1, 10, 100], 'gamma': [1, 10, 100]}, verbose=3)

In [31]:
gs.best_estimator_

SVC(C=1, gamma=1, kernel='linear')