### Importing Required Libraries

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

### Installing Required Libraries

In [23]:
# !pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (0.23.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (1.14.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (2.1.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (1.6.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (3.9.3)
Requirement already satisfied: joblib>=0.13.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.55.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
# importing libraries
from mlxtend.frequent_patterns import apriori,association_rules

### Reading and Understanding

In [25]:
df = pd.read_csv('GroceryStoreDataSet.csv',header=None,names = ['Products'])
df.head()

                        Products
0             MILK,BREAD,BISCUIT
1  BREAD,MILK,BISCUIT,CORNFLAKES
2            BREAD,TEA,BOURNVITA
3           JAM,MAGGI,BREAD,MILK
4              MAGGI,TEA,BISCUIT

In [26]:
product = 'MILK,BREAD,BISCUIT'
product.split()

['MILK,BREAD,BISCUIT']

In [27]:
# creating function 
def breakproductname(data):
    return data.split(',')

# calling the function
breakproductname(product)

['MILK', 'BREAD', 'BISCUIT']

In [28]:
data = list(df['Products'].apply(breakproductname))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COKE', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COKE', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COKE'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

In [29]:
# importing class for encoding
from mlxtend.preprocessing import TransactionEncoder

# creating instance
te = TransactionEncoder()

# encoding
enddata = te.fit_transform(data)

In [32]:
print(te.columns_)

['BISCUIT', 'BOURNVITA', 'BREAD', 'COFFEE', 'COKE', 'CORNFLAKES', 'JAM', 'MAGGI', 'MILK', 'SUGER', 'TEA']

In [33]:
data[0]

['MILK', 'BREAD', 'BISCUIT']

In [30]:
print(enddata)

[[ True False  True False False False False False  True False False]
 [ True False  True False False  True False False  True False False]
 [False  True  True False False False False False False False  True]
 [False False  True False False False  True  True  True False False]
 [ True False False False False False False  True False False  True]
 [False  True  True False False False False False False False  True]
 [False False False False False  True False  True False False  True]
 [ True False  True False False False False  True False False  True]
 [False False  True False False False  True  True False False  True]
 [False False  True False False False False False  True False False]
 [ True False False  True  True  True False False False False False]
 [ True False False  True  True  True False False False False False]
 [False  True False  True False False False False False  True False]
 [False False  True  True  True False False False False False False]
 [ True False  True False False False False False False  True False]
 [False False False  True False  True False False False  True False]
 [False  True  True False False False False False False  True False]
 [False False  True  True False False False False False  True False]
 [False False  True  True False False False False False  True False]
 [False False False  True False  True False False  True False  True]]

In [36]:
df = pd.DataFrame(enddata,columns=te.columns_)
df.replace(True,1,inplace=True)
df.replace(False,0,inplace=True)

In [37]:
df

,BISCUIT,BOURNVITA,BREAD,COFFEE,COKE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,1,0,1,0,0,0,0,0,1,0,0
1,1,0,1,0,0,1,0,0,1,0,0
2,0,1,1,0,0,0,0,0,0,0,1
3,0,0,1,0,0,0,1,1,1,0,0
4,1,0,0,0,0,0,0,1,0,0,1
5,0,1,1,0,0,0,0,0,0,0,1
6,0,0,0,0,0,1,0,1,0,0,1
7,1,0,1,0,0,0,0,1,0,0,1
8,0,0,1,0,0,0,1,1,0,0,1
9,0,0,1,0,0,0,0,0,1,0,0
10,1,0,0,1,1,1,0,0,0,0,0
11,1,0,0,1,1,1,0,0,0,0,0
12,0,1,0,1,0,0,0,0,0,1,0
13,0,0,1,1,1,0,0,0,0,0,0
14,1,0,1,0,0,0,0,0,0,1,0
15,0,0,0,1,0,1,0,0,0,1,0
16,0,1,1,0,0,0,0,0,0,1,0
17,0,0,1,1,0,0,0,0,0,1,0
18,0,0,1,1,0,0,0,0,0,1,0
19,0,0,0,1,0,1,0,0,1,0,1

### Model

In [45]:
score = apriori(df,min_support=0.2,use_colnames=True)
score

    support              itemsets
0      0.35             (BISCUIT)
1      0.20           (BOURNVITA)
2      0.65               (BREAD)
3      0.40              (COFFEE)
4      0.30          (CORNFLAKES)
5      0.25               (MAGGI)
6      0.25                (MILK)
7      0.30               (SUGER)
8      0.35                 (TEA)
9      0.20      (BREAD, BISCUIT)
10     0.20         (BREAD, MILK)
11     0.20        (SUGER, BREAD)
12     0.20          (TEA, BREAD)
13     0.20  (CORNFLAKES, COFFEE)
14     0.20       (SUGER, COFFEE)
15     0.20          (MAGGI, TEA)

In [52]:
score_ar = association_rules(score,metric='confidence',min_threshold=0.5,num_itemsets='int')
score_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(BISCUIT),(BREAD),0.35,0.65,0.2,0.571429,0.879121,1.0,-0.0275,0.816667,-0.174603,0.250000,-0.224490,0.439560
1,(MILK),(BREAD),0.25,0.65,0.2,0.800000,1.230769,1.0,0.0375,1.750000,0.250000,0.285714,0.428571,0.553846
2,(SUGER),(BREAD),0.30,0.65,0.2,0.666667,1.025641,1.0,0.0050,1.050000,0.035714,0.266667,0.047619,0.487179
3,(TEA),(BREAD),0.35,0.65,0.2,0.571429,0.879121,1.0,-0.0275,0.816667,-0.174603,0.250000,-0.224490,0.439560
4,(CORNFLAKES),(COFFEE),0.30,0.40,0.2,0.666667,1.666667,1.0,0.0800,1.800000,0.571429,0.400000,0.444444,0.583333
5,(COFFEE),(CORNFLAKES),0.40,0.30,0.2,0.500000,1.666667,1.0,0.0800,1.400000,0.666667,0.400000,0.285714,0.583333
6,(SUGER),(COFFEE),0.30,0.40,0.2,0.666667,1.666667,1.0,0.0800,1.800000,0.571429,0.400000,0.444444,0.583333
7,(COFFEE),(SUGER),0.40,0.30,0.2,0.500000,1.666667,1.0,0.0800,1.400000,0.666667,0.400000,0.285714,0.583333
8,(MAGGI),(TEA),0.25,0.35,0.2,0.800000,2.285714,1.0,0.1125,3.250000,0.750000,0.500000,0.692308,0.685714
9,(TEA),(MAGGI),0.35,0.25,0.2,0.571429,2.285714,1.0,0.1125,1.750000,0.865385,0.500000,0.428571,0.685714