### Importing Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

### Reading and Understanding

In [2]:
df = pd.read_csv('data_titanic.csv')
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Initial
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [3]:
# Shape
df.shape

(891, 14)

In [4]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Name         891 non-null    object
 5   Sex          891 non-null    object
 6   Age          891 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    object
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    object
 12  Embarked     891 non-null    object
 13  Initial      891 non-null    object
dtypes: float64(2), int64(6), object(6)
memory usage: 97.6+ KB

In [5]:
# Checking Imbalanced 
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [6]:
# Missing values
df.isnull().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
Initial          0
dtype: int64

### Data Wrangling

In [7]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Initial'],
      dtype='object')

In [10]:
df.groupby('Sex')['Survived'].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [11]:
# dropping columns
df.drop(columns = ['Unnamed: 0','PassengerId','Name','Ticket', 'Fare', 'Cabin','Initial'],inplace=True)

In [12]:
# info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Embarked  891 non-null    object
dtypes: float64(1), int64(4), object(2)
memory usage: 48.9+ KB

In [13]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

### Encoding Data

In [15]:
# importing class
from sklearn.preprocessing import LabelEncoder

# creating instance
lr = LabelEncoder()

# transform
df['Sex'] = lr.fit_transform(df['Sex'])
df['Embarked'] = lr.fit_transform(df['Embarked'])

In [16]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    1  22.0      1      0         2
1         1       1    0  38.0      1      0         0
2         1       3    0  26.0      0      0         2
3         1       1    0  35.0      1      0         2
4         0       3    1  35.0      0      0         2

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Embarked  891 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 48.9 KB

### split data into x and y

In [19]:
x = df.drop(columns = 'Survived')
y = df['Survived']

### splitting data into train and test

In [20]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=1)

### Model1 : Bagging

In [28]:
# import ensemble class
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
# create instance
bg = BaggingClassifier(LogisticRegression())

# fit
bg.fit(xtrain,ytrain)

# predict
ypred = bg.predict(xtest)

# Accuracy
print(f'Training Score: {bg.score(xtrain,ytrain)}')
print(f'Testing Score: {bg.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.8019662921348315
Testing Score: 0.8044692737430168
Classification Report
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       106
           1       0.77      0.74      0.76        73

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

### Model2 : Bagging

In [29]:
# import ensemble class
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
# create instance
bg = BaggingClassifier(DecisionTreeClassifier())

# fit
bg.fit(xtrain,ytrain)

# predict
ypred = bg.predict(xtest)

# Accuracy
print(f'Training Score: {bg.score(xtrain,ytrain)}')
print(f'Testing Score: {bg.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.9396067415730337
Testing Score: 0.7877094972067039
Classification Report
              precision    recall  f1-score   support

           0       0.79      0.88      0.83       106
           1       0.79      0.66      0.72        73

    accuracy                           0.79       179
   macro avg       0.79      0.77      0.77       179
weighted avg       0.79      0.79      0.78       179

### Model3 : Randomforest

In [31]:
# import ensemble class
from sklearn.ensemble import RandomForestClassifier
# create instance
bg = RandomForestClassifier()

# fit
bg.fit(xtrain,ytrain)

# predict
ypred = bg.predict(xtest)

# Accuracy
print(f'Training Score: {bg.score(xtrain,ytrain)}')
print(f'Testing Score: {bg.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.952247191011236
Testing Score: 0.770949720670391
Classification Report
              precision    recall  f1-score   support

           0       0.79      0.83      0.81       106
           1       0.74      0.68      0.71        73

    accuracy                           0.77       179
   macro avg       0.76      0.76      0.76       179
weighted avg       0.77      0.77      0.77       179

### Voting Classifier

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [33]:
# estimators : list of (str, estimator) tuples
model = []
model.append(('LogisticRegression',LogisticRegression()))
model.append(('KNeighborsClassifier',KNeighborsClassifier()))
model.append(('DecisionTreeClassifier',DecisionTreeClassifier()))

In [34]:
model

[('LogisticRegression', LogisticRegression()),
 ('KNeighborsClassifier', KNeighborsClassifier()),
 ('DecisionTreeClassifier', DecisionTreeClassifier())]

In [37]:
# voting classifier
from sklearn.ensemble import VotingClassifier

# instance of class
vc = VotingClassifier(estimators = model)

# fit
vc.fit(xtrain,ytrain)

# predict
ypred = vc.predict(xtest)

# Accuracy
print(f'Training Score: {vc.score(xtrain,ytrain)}')
print(f'Testing Score: {vc.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.9030898876404494
Testing Score: 0.7877094972067039
Classification Report
              precision    recall  f1-score   support

           0       0.79      0.88      0.83       106
           1       0.79      0.66      0.72        73

    accuracy                           0.79       179
   macro avg       0.79      0.77      0.77       179
weighted avg       0.79      0.79      0.78       179

### Boosting

In [39]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(xtrain,ytrain)

ypred = ada.predict(xtest)

# Accuracy
print(f'Training Score: {ada.score(xtrain,ytrain)}')
print(f'Testing Score: {ada.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.8258426966292135
Testing Score: 0.7988826815642458
Classification Report
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       106
           1       0.78      0.70      0.74        73

    accuracy                           0.80       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.80      0.80      0.80       179

### Gradient Boosting

In [40]:
from sklearn.ensemble import GradientBoostingClassifier

ada_gbc = GradientBoostingClassifier()

ada_gbc.fit(xtrain,ytrain)

ypred = ada_gbc.predict(xtest)

# Accuracy
print(f'Training Score: {ada_gbc.score(xtrain,ytrain)}')
print(f'Testing Score: {ada_gbc.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.8862359550561798
Testing Score: 0.7821229050279329
Classification Report
              precision    recall  f1-score   support

           0       0.77      0.91      0.83       106
           1       0.81      0.60      0.69        73

    accuracy                           0.78       179
   macro avg       0.79      0.75      0.76       179
weighted avg       0.79      0.78      0.77       179

### Xtream Gradient Boosting

In [41]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-2.1.3-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (2.1.1)
Requirement already satisfied: scipy in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (1.14.1)
Downloading xgboost-2.1.3-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.8/124.9 MB 2.4 MB/s eta 0:00:52
   ---------------------------------------- 1.3/124.9 MB 2.4 MB/s eta 0:00:52
    --------------------------------------- 1.8/124.9 MB 2.4 MB/s eta 0:00:52
    --------------------------------------- 2.4/124.9 MB 2.4 MB/s eta 0:00:53
    --------------------------------------- 2.6/124.9 MB 2.3 MB/s eta 0:00:54
   - -------------------------------------- 3.4/124.9 MB 2.4 MB/s eta 0:00:51
   - -------------------------------------- 4.2/124.9 MB 2.6 MB/s eta 0:00:48
   - -------------------------------------- 4.7/124.9 MB 2.5 MB/s eta 0:00:48
   - -------------------------------------- 5.2/124.9 MB 2.6 MB/s eta 0:00:47
   - -------------------------------------- 6.0/124.9 MB 2.7 MB/s eta 0:00:44
   -- ------------------------------------- 7.1/124.9 MB 2.8 MB/s eta 0:00:42
   -- ------------------------------------- 7.3/124.9 MB 2.8 MB/s eta 0:00:43
   -- ------------------------------------- 7.9/124.9 MB 2.7 MB/s eta 0:00:43
   -- ------------------------------------- 8.4/124.9 MB 2.7 MB/s eta 0:00:43
   -- ------------------------------------- 8.9/124.9 MB 2.7 MB/s eta 0:00:44
   -- ------------------------------------- 9.2/124.9 MB 2.6 MB/s eta 0:00:45
   --- ------------------------------------ 9.7/124.9 MB 2.6 MB/s eta 0:00:45
   --- ------------------------------------ 10.0/124.9 MB 2.6 MB/s eta 0:00:45
   --- ------------------------------------ 10.2/124.9 MB 2.4 MB/s eta 0:00:48
   --- ------------------------------------ 10.5/124.9 MB 2.4 MB/s eta 0:00:48
   --- ------------------------------------ 10.7/124.9 MB 2.4 MB/s eta 0:00:48
   --- ------------------------------------ 11.0/124.9 MB 2.3 MB/s eta 0:00:51
   --- ------------------------------------ 11.0/124.9 MB 2.3 MB/s eta 0:00:51
   --- ------------------------------------ 11.3/124.9 MB 2.1 MB/s eta 0:00:54
   --- ------------------------------------ 11.5/124.9 MB 2.1 MB/s eta 0:00:55
   --- ------------------------------------ 11.5/124.9 MB 2.1 MB/s eta 0:00:55
   --- ------------------------------------ 11.8/124.9 MB 2.0 MB/s eta 0:00:57
   --- ------------------------------------ 12.1/124.9 MB 2.0 MB/s eta 0:00:58
   --- ------------------------------------ 12.3/124.9 MB 1.9 MB/s eta 0:00:59
   --- ------------------------------------ 12.3/124.9 MB 1.9 MB/s eta 0:00:59
   ---- ----------------------------------- 12.6/124.9 MB 1.9 MB/s eta 0:00:59
   ---- ----------------------------------- 12.8/124.9 MB 1.9 MB/s eta 0:01:01
   ---- ----------------------------------- 13.1/124.9 MB 1.8 MB/s eta 0:01:02
   ---- ----------------------------------- 13.4/124.9 MB 1.8 MB/s eta 0:01:02
   ---- ----------------------------------- 13.6/124.9 MB 1.8 MB/s eta 0:01:02
   ---- ----------------------------------- 14.2/124.9 MB 1.8 MB/s eta 0:01:02
   ---- ----------------------------------- 14.4/124.9 MB 1.8 MB/s eta 0:01:01
   ---- ----------------------------------- 15.2/124.9 MB 1.8 MB/s eta 0:01:00
   ----- ---------------------------------- 15.7/124.9 MB 1.9 MB/s eta 0:00:59
   ----- ---------------------------------- 16.3/124.9 MB 1.9 MB/s eta 0:00:58
   ----- ---------------------------------- 16.5/124.9 MB 1.9 MB/s eta 0:00:58
   ----- ---------------------------------- 16.8/124.9 MB 1.9 MB/s eta 0:00:59
   ----- ---------------------------------- 17.0/124.9 MB 1.8 MB/s eta 0:00:59
   ----- ---------------------------------- 17.3/124.9 MB 1.8 MB/s eta 0:01:00
   ----- ---------------------------------- 17.6/124.9 MB 1.8 MB/s eta 0:01:00
   ----- ---------------------------------- 17.8/124.9 MB 1.8 MB/s eta 0:01:00
   ----- ---------------------------------- 18.1/124.9 MB 1.8 MB/s eta 0:01:01
   ----- ---------------------------------- 18.1/124.9 MB 1.8 MB/s eta 0:01:01
   ----- ---------------------------------- 18.4/124.9 MB 1.8 MB/s eta 0:01:01
   ----- ---------------------------------- 18.6/124.9 MB 1.7 MB/s eta 0:01:01
   ------ --------------------------------- 19.1/124.9 MB 1.8 MB/s eta 0:01:01
   ------ --------------------------------- 19.7/124.9 MB 1.8 MB/s eta 0:01:00
   ------ --------------------------------- 19.7/124.9 MB 1.8 MB/s eta 0:01:00
   ------ --------------------------------- 19.9/124.9 MB 1.7 MB/s eta 0:01:02
   ------ --------------------------------- 19.9/124.9 MB 1.7 MB/s eta 0:01:02
   ------ --------------------------------- 19.9/124.9 MB 1.7 MB/s eta 0:01:02
   ------ --------------------------------- 20.2/124.9 MB 1.7 MB/s eta 0:01:04
   ------ --------------------------------- 20.4/124.9 MB 1.6 MB/s eta 0:01:05
   ------ --------------------------------- 20.4/124.9 MB 1.6 MB/s eta 0:01:05
   ------ --------------------------------- 20.7/124.9 MB 1.6 MB/s eta 0:01:06
   ------ --------------------------------- 20.7/124.9 MB 1.6 MB/s eta 0:01:06
   ------ --------------------------------- 21.0/124.9 MB 1.6 MB/s eta 0:01:06
   ------ --------------------------------- 21.2/124.9 MB 1.6 MB/s eta 0:01:07
   ------ --------------------------------- 21.2/124.9 MB 1.6 MB/s eta 0:01:07
   ------ --------------------------------- 21.5/124.9 MB 1.5 MB/s eta 0:01:08
   ------ --------------------------------- 21.8/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 22.0/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 22.0/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 22.3/124.9 MB 1.5 MB/s eta 0:01:09
   ------- -------------------------------- 22.5/124.9 MB 1.5 MB/s eta 0:01:09
   ------- -------------------------------- 22.5/124.9 MB 1.5 MB/s eta 0:01:09
   ------- -------------------------------- 23.1/124.9 MB 1.5 MB/s eta 0:01:09
   ------- -------------------------------- 23.3/124.9 MB 1.5 MB/s eta 0:01:09
   ------- -------------------------------- 23.9/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 24.4/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 24.4/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 24.6/124.9 MB 1.5 MB/s eta 0:01:08
   ------- -------------------------------- 24.9/124.9 MB 1.5 MB/s eta 0:01:08
   -------- ------------------------------- 25.2/124.9 MB 1.5 MB/s eta 0:01:08
   -------- ------------------------------- 25.4/124.9 MB 1.5 MB/s eta 0:01:08
   -------- ------------------------------- 25.4/124.9 MB 1.5 MB/s eta 0:01:08
   -------- ------------------------------- 26.2/124.9 MB 1.5 MB/s eta 0:01:07
   -------- ------------------------------- 26.7/124.9 MB 1.5 MB/s eta 0:01:06
   -------- ------------------------------- 27.0/124.9 MB 1.5 MB/s eta 0:01:06
   -------- ------------------------------- 27.3/124.9 MB 1.5 MB/s eta 0:01:06
   -------- ------------------------------- 27.5/124.9 MB 1.5 MB/s eta 0:01:06
   -------- ------------------------------- 28.0/124.9 MB 1.5 MB/s eta 0:01:05
   --------- ------------------------------ 28.3/124.9 MB 1.5 MB/s eta 0:01:05
   --------- ------------------------------ 28.6/124.9 MB 1.5 MB/s eta 0:01:05
   --------- ------------------------------ 29.1/124.9 MB 1.5 MB/s eta 0:01:05
   --------- ------------------------------ 29.4/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 29.6/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 29.9/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 30.1/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 30.4/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 30.7/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 30.9/124.9 MB 1.5 MB/s eta 0:01:04
   --------- ------------------------------ 31.2/124.9 MB 1.5 MB/s eta 0:01:04
   ---------- ----------------------------- 31.7/124.9 MB 1.5 MB/s eta 0:01:03
   ---------- ----------------------------- 32.5/124.9 MB 1.5 MB/s eta 0:01:02
   ---------- ----------------------------- 33.0/124.9 MB 1.5 MB/s eta 0:01:01
   ---------- ----------------------------- 33.6/124.9 MB 1.5 MB/s eta 0:01:00
   ---------- ----------------------------- 34.1/124.9 MB 1.5 MB/s eta 0:01:00
   ---------- ----------------------------- 34.3/124.9 MB 1.5 MB/s eta 0:00:59
   ----------- ---------------------------- 35.1/124.9 MB 1.6 MB/s eta 0:00:58
   ----------- ---------------------------- 35.9/124.9 MB 1.6 MB/s eta 0:00:57
   ----------- ---------------------------- 36.4/124.9 MB 1.6 MB/s eta 0:00:56
   ----------- ---------------------------- 37.2/124.9 MB 1.6 MB/s eta 0:00:55
   ------------ --------------------------- 37.7/124.9 MB 1.6 MB/s eta 0:00:55
   ------------ --------------------------- 38.3/124.9 MB 1.6 MB/s eta 0:00:54
   ------------ --------------------------- 39.1/124.9 MB 1.6 MB/s eta 0:00:53
   ------------ --------------------------- 39.3/124.9 MB 1.6 MB/s eta 0:00:53
   ------------ --------------------------- 39.8/124.9 MB 1.6 MB/s eta 0:00:52
   ------------- -------------------------- 41.2/124.9 MB 1.7 MB/s eta 0:00:51
   ------------- -------------------------- 41.9/124.9 MB 1.7 MB/s eta 0:00:50
   ------------- -------------------------- 42.7/124.9 MB 1.7 MB/s eta 0:00:49
   ------------- -------------------------- 43.3/124.9 MB 1.7 MB/s eta 0:00:48
   -------------- ------------------------- 44.0/124.9 MB 1.7 MB/s eta 0:00:47
   -------------- ------------------------- 44.3/124.9 MB 1.7 MB/s eta 0:00:47
   -------------- ------------------------- 44.8/124.9 MB 1.7 MB/s eta 0:00:47
   -------------- ------------------------- 45.4/124.9 MB 1.7 MB/s eta 0:00:46
   -------------- ------------------------- 45.9/124.9 MB 1.7 MB/s eta 0:00:46
   -------------- ------------------------- 46.4/124.9 MB 1.8 MB/s eta 0:00:45
   --------------- ------------------------ 46.9/124.9 MB 1.8 MB/s eta 0:00:45
   --------------- ------------------------ 47.7/124.9 MB 1.8 MB/s eta 0:00:44
   --------------- ------------------------ 48.5/124.9 MB 1.8 MB/s eta 0:00:43
   --------------- ------------------------ 49.3/124.9 MB 1.8 MB/s eta 0:00:42
   ---------------- ----------------------- 50.1/124.9 MB 1.8 MB/s eta 0:00:42
   ---------------- ----------------------- 50.9/124.9 MB 1.8 MB/s eta 0:00:41
   ---------------- ----------------------- 51.6/124.9 MB 1.8 MB/s eta 0:00:40
   ---------------- ----------------------- 52.4/124.9 MB 1.9 MB/s eta 0:00:39
   ----------------- ---------------------- 53.2/124.9 MB 1.9 MB/s eta 0:00:39
   ----------------- ---------------------- 54.0/124.9 MB 1.9 MB/s eta 0:00:38
   ----------------- ---------------------- 54.5/124.9 MB 1.9 MB/s eta 0:00:38
   ----------------- ---------------------- 55.3/124.9 MB 1.9 MB/s eta 0:00:37
   ------------------ --------------------- 56.4/124.9 MB 1.9 MB/s eta 0:00:36
   ------------------ --------------------- 57.1/124.9 MB 1.9 MB/s eta 0:00:35
   ------------------ --------------------- 57.9/124.9 MB 2.0 MB/s eta 0:00:35
   ------------------ --------------------- 58.2/124.9 MB 2.0 MB/s eta 0:00:35
   ------------------ --------------------- 59.0/124.9 MB 2.0 MB/s eta 0:00:34
   ------------------- -------------------- 59.5/124.9 MB 2.0 MB/s eta 0:00:34
   ------------------- -------------------- 60.3/124.9 MB 2.0 MB/s eta 0:00:33
   ------------------- -------------------- 60.8/124.9 MB 2.0 MB/s eta 0:00:33
   ------------------- -------------------- 61.6/124.9 MB 2.0 MB/s eta 0:00:33
   ------------------- -------------------- 62.4/124.9 MB 2.0 MB/s eta 0:00:32
   -------------------- ------------------- 63.2/124.9 MB 2.0 MB/s eta 0:00:31
   -------------------- ------------------- 63.7/124.9 MB 2.0 MB/s eta 0:00:31
   -------------------- ------------------- 64.5/124.9 MB 2.0 MB/s eta 0:00:31
   -------------------- ------------------- 65.3/124.9 MB 2.0 MB/s eta 0:00:30
   --------------------- ------------------ 66.1/124.9 MB 2.0 MB/s eta 0:00:30
   --------------------- ------------------ 67.1/124.9 MB 2.0 MB/s eta 0:00:29
   --------------------- ------------------ 67.9/124.9 MB 2.0 MB/s eta 0:00:29
   --------------------- ------------------ 68.4/124.9 MB 2.0 MB/s eta 0:00:28
   ---------------------- ----------------- 68.9/124.9 MB 2.0 MB/s eta 0:00:28
   ---------------------- ----------------- 69.5/124.9 MB 2.0 MB/s eta 0:00:28
   ---------------------- ----------------- 70.0/124.9 MB 2.0 MB/s eta 0:00:28
   ---------------------- ----------------- 70.3/124.9 MB 2.0 MB/s eta 0:00:27
   ---------------------- ----------------- 70.8/124.9 MB 2.0 MB/s eta 0:00:27
   ---------------------- ----------------- 71.3/124.9 MB 2.0 MB/s eta 0:00:27
   ----------------------- ---------------- 72.1/124.9 MB 2.1 MB/s eta 0:00:26
   ----------------------- ---------------- 72.6/124.9 MB 2.1 MB/s eta 0:00:26
   ----------------------- ---------------- 73.1/124.9 MB 2.1 MB/s eta 0:00:25
   ----------------------- ---------------- 73.9/124.9 MB 2.1 MB/s eta 0:00:25
   ----------------------- ---------------- 74.4/124.9 MB 2.1 MB/s eta 0:00:24
   ----------------------- ---------------- 74.7/124.9 MB 2.1 MB/s eta 0:00:24
   ------------------------ --------------- 75.2/124.9 MB 2.1 MB/s eta 0:00:24
   ------------------------ --------------- 75.8/124.9 MB 2.1 MB/s eta 0:00:23
   ------------------------ --------------- 76.3/124.9 MB 2.1 MB/s eta 0:00:23
   ------------------------ --------------- 77.1/124.9 MB 2.2 MB/s eta 0:00:23
   ------------------------ --------------- 77.6/124.9 MB 2.2 MB/s eta 0:00:22
   ------------------------- -------------- 78.1/124.9 MB 2.2 MB/s eta 0:00:22
   ------------------------- -------------- 78.6/124.9 MB 2.2 MB/s eta 0:00:22
   ------------------------- -------------- 79.2/124.9 MB 2.2 MB/s eta 0:00:21
   ------------------------- -------------- 79.4/124.9 MB 2.2 MB/s eta 0:00:21
   ------------------------- -------------- 80.0/124.9 MB 2.2 MB/s eta 0:00:21
   ------------------------- -------------- 80.5/124.9 MB 2.2 MB/s eta 0:00:21
   ------------------------- -------------- 81.0/124.9 MB 2.2 MB/s eta 0:00:20
   -------------------------- ------------- 81.5/124.9 MB 2.2 MB/s eta 0:00:20
   -------------------------- ------------- 82.1/124.9 MB 2.2 MB/s eta 0:00:20
   -------------------------- ------------- 82.3/124.9 MB 2.2 MB/s eta 0:00:20
   -------------------------- ------------- 82.6/124.9 MB 2.2 MB/s eta 0:00:20
   -------------------------- ------------- 83.1/124.9 MB 2.2 MB/s eta 0:00:19
   -------------------------- ------------- 83.4/124.9 MB 2.2 MB/s eta 0:00:19
   -------------------------- ------------- 83.9/124.9 MB 2.2 MB/s eta 0:00:19
   -------------------------- ------------- 84.1/124.9 MB 2.2 MB/s eta 0:00:19
   --------------------------- ------------ 84.7/124.9 MB 2.2 MB/s eta 0:00:18
   --------------------------- ------------ 85.2/124.9 MB 2.2 MB/s eta 0:00:18
   --------------------------- ------------ 85.7/124.9 MB 2.3 MB/s eta 0:00:18
   --------------------------- ------------ 86.2/124.9 MB 2.3 MB/s eta 0:00:18
   --------------------------- ------------ 86.8/124.9 MB 2.3 MB/s eta 0:00:17
   --------------------------- ------------ 87.0/124.9 MB 2.3 MB/s eta 0:00:17
   ---------------------------- ----------- 87.6/124.9 MB 2.3 MB/s eta 0:00:17
   ---------------------------- ----------- 88.1/124.9 MB 2.3 MB/s eta 0:00:17
   ---------------------------- ----------- 88.3/124.9 MB 2.3 MB/s eta 0:00:16
   ---------------------------- ----------- 88.9/124.9 MB 2.3 MB/s eta 0:00:16
   ---------------------------- ----------- 89.1/124.9 MB 2.3 MB/s eta 0:00:16
   ---------------------------- ----------- 89.7/124.9 MB 2.3 MB/s eta 0:00:16
   ---------------------------- ----------- 89.9/124.9 MB 2.3 MB/s eta 0:00:16
   ----------------------------- ---------- 90.7/124.9 MB 2.4 MB/s eta 0:00:15
   ----------------------------- ---------- 91.2/124.9 MB 2.4 MB/s eta 0:00:15
   ----------------------------- ---------- 91.8/124.9 MB 2.4 MB/s eta 0:00:14
   ----------------------------- ---------- 92.3/124.9 MB 2.4 MB/s eta 0:00:14
   ----------------------------- ---------- 92.8/124.9 MB 2.4 MB/s eta 0:00:14
   ----------------------------- ---------- 93.6/124.9 MB 2.4 MB/s eta 0:00:13
   ------------------------------ --------- 94.1/124.9 MB 2.4 MB/s eta 0:00:13
   ------------------------------ --------- 94.9/124.9 MB 2.4 MB/s eta 0:00:13
   ------------------------------ --------- 95.7/124.9 MB 2.5 MB/s eta 0:00:12
   ------------------------------ --------- 96.2/124.9 MB 2.5 MB/s eta 0:00:12
   ------------------------------- -------- 97.0/124.9 MB 2.5 MB/s eta 0:00:12
   ------------------------------- -------- 97.5/124.9 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 97.8/124.9 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 98.6/124.9 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 99.4/124.9 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 99.9/124.9 MB 2.5 MB/s eta 0:00:10
   -------------------------------- ------- 100.9/124.9 MB 2.6 MB/s eta 0:00:10
   -------------------------------- ------- 101.7/124.9 MB 2.6 MB/s eta 0:00:09
   -------------------------------- ------- 102.5/124.9 MB 2.6 MB/s eta 0:00:09
   --------------------------------- ------ 103.3/124.9 MB 2.6 MB/s eta 0:00:09
   --------------------------------- ------ 104.1/124.9 MB 2.6 MB/s eta 0:00:08
   --------------------------------- ------ 104.3/124.9 MB 2.6 MB/s eta 0:00:08
   --------------------------------- ------ 105.4/124.9 MB 2.7 MB/s eta 0:00:08
   --------------------------------- ------ 106.2/124.9 MB 2.7 MB/s eta 0:00:08
   ---------------------------------- ----- 106.7/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 107.2/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 107.5/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 107.7/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 108.0/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 108.3/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 108.5/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 108.8/124.9 MB 2.7 MB/s eta 0:00:07
   ----------------------------------- ---- 109.3/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 109.8/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 110.4/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 110.4/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 110.9/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 110.9/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 111.1/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 111.4/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 111.7/124.9 MB 2.7 MB/s eta 0:00:05
   ----------------------------------- ---- 111.9/124.9 MB 2.7 MB/s eta 0:00:05
   ----------------------------------- ---- 112.2/124.9 MB 2.7 MB/s eta 0:00:05
   ------------------------------------ --- 112.5/124.9 MB 2.7 MB/s eta 0:00:05
   ------------------------------------ --- 112.7/124.9 MB 2.6 MB/s eta 0:00:05
   ------------------------------------ --- 113.2/124.9 MB 2.6 MB/s eta 0:00:05
   ------------------------------------ --- 113.5/124.9 MB 2.6 MB/s eta 0:00:05

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
from xgboost import XGBClassifier

xgb = XGBClassifier()

xgb.fit(xtrain,ytrain)

ypred = xgb.predict(xtest)

# Accuracy
print(f'Training Score: {xgb.score(xtrain,ytrain)}')
print(f'Testing Score: {xgb.score(xtest,ytest)}')

# classification report
from sklearn.metrics import classification_report
print('Classification Report')
print(classification_report(ytest,ypred))

Training Score: 0.9339887640449438
Testing Score: 0.7932960893854749
Classification Report
              precision    recall  f1-score   support

           0       0.79      0.89      0.84       106
           1       0.80      0.66      0.72        73

    accuracy                           0.79       179
   macro avg       0.79      0.77      0.78       179
weighted avg       0.79      0.79      0.79       179